In [1]:
import numpy as np


In [2]:
ls = [[2,3],[3,4],[5,6,]]
ls2 =[[[2,3],[3,4]],[[2,3],[4,5]]]




In [12]:
a = np.array([1,2,3,4,5,6])

In [13]:
print(type(a))
print(a)
print(a.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5 6]
(6,)


In [18]:
a = a.reshape(-1,1)
print(a.shape)

(6, 1)


In [7]:
a = np.array([[1],[2],[3],[4],[5]])
print(a.shape)

(5, 1)


In [38]:
a1 = np.zeros((3,4) , dtype="uint32")
print(a1)
a2 = np.ones((2,3))
print(a2)
a3 = np.eye(4)
print(a3)
a4 = np.full((4,3),5)
print(a4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [26]:
print(5+np.zeros((4,3)))

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [39]:
a2.dtype

dtype('float64')

In [44]:
n1 = np.array([1,2,3,4])
n2 = np.array([2,3,4,5])
print(n1+n2)
print(n2-n1)
print(np.add(n1,n2))
print(np.subtract(n2,n1))

[3 5 7 9]
[1 1 1 1]
[3 5 7 9]
[1 1 1 1]


In [47]:
print(n1*n2)
print(n2/n1)
print(np.multiply(n1,n2))
print(np.divide(n1,n2))

[ 2  6 12 20]
[2.         1.5        1.33333333 1.25      ]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]


In [48]:
print(np.sum(n1))

10


In [52]:
n3 = np.array([[1,2],[4,6]])
print(np.sum(n3 , axis =1))
print(np.sum(n3 , axis =0))

[ 3 10]
[5 8]


In [56]:
n4 = np.array([2,3,4,5,6,7])
print(n4[2:5])

[4 5 6]


In [62]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
np.stack((a,b) , axis=1)

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [63]:
np.stack((a,b) , axis=0)

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [65]:
np.hstack((a,b))

array([1, 2, 3, 4, 2, 3, 4, 5])

In [69]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [75]:
# operations
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.std(a)**2)
print(np.var(a))
print(np.min(a))
print(np.max(a))


5.0
5.0
2.581988897471611
6.666666666666666
6.666666666666667
1
9


In [78]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.mean(a, axis=0))

[3.5 4.5 5.5 6.5 7.5]


In [141]:
# random
np.random.seed(21)
np.random.randint(5,40,5)


array([14, 20,  9, 39, 15])

In [142]:
np.random.randn(3,5)

array([[-0.43620115,  0.94579408, -0.41222702,  0.41100197, -0.92408663],
       [-0.08541553, -0.59903194,  1.30411598,  0.46642603, -0.07417733],
       [ 0.61655702, -1.63565101, -1.86823213, -0.00467674,  1.01913838]])

In [144]:
a = np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(a)
print(a)

[6 4 2 9 8 5 7 3 1]


In [152]:
# np.random.seed(7)
print(np.random.choice(a))

8


In [154]:
np.array?